version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:latest
    container_name: ids_mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - ids_network

  # Node.js Backend API
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ids_backend
    restart: unless-stopped
    ports:
      - "5011:5011"
    environment:
      - PORT=5011
      - MONGODB_URI=mongodb://mongodb:27017/student_management
      - JWT_SECRET=smkn1_siswa_jwt_secret_key_2026_secure
    depends_on:
      - mongodb
    networks:
      - ids_network


volumes:
  mongodb_data:

networks:
  ids_network:
    driver: bridge
